!function(){var _={};function t(){var t=_XAPP_.getItem("downloads");if(0!=t.length){var e=document.querySelector("#download-list");e.innerHTML="";for(var o,n,a,d=0;d<t.length;d++){var s=t[d];o=s,a=n=void 0,(n=document.createElement("li")).setAttribute("class","list-view-item"),n.setAttribute("data-download-id",o.download_id),n.setAttribute("id",o.download_id),a="icon "+fileType2Icon(o.file_type),_[o.download_id]=new Progress.bar({id:"_bar_"+o.download_id,autoRemove:!0,backgroundSpeed:5,type:"charge",showPercentage:!0}),n.innerHTML=`
                <div class="${a}"></div>
                <div class="item-info">
                    <div class="item-title">${o.file_name}</div>   
                    <div class="progress-bar">
                    </div>  
                    <div class="meta-info">
                        <span id="download-sofar"></span><span id="download-speed"></span>
                    </div>
                </div>
                <button class="menu-button"></button>
        `,n.querySelector(".menu-button").addEventListener("click",function(t){var e=this.getAttribute("data-status"),o=this.parentElement.getAttribute("data-download-id");e<=1?_XAPP_.dispatchEvent("event_page_to_app",{transId:"pause_download",downloadId:o}):2!=e&&3==e?_XAPP_.dispatchEvent("event_page_to_app",{transId:"show_download_menu",downloadId:o}):_XAPP_.dispatchEvent("event_page_to_app",{transId:"resume_download",downloadId:o}),t.stopPropagation(),t.preventDefault()}),n.addEventListener("click",function(t){var e=this.getAttribute("data-download-id");_XAPP_.dispatchEvent("event_page_to_app",{transId:"open_download",downloadId:e})}),e.appendChild(n),i(s.download_id)}}else emptyContent()}function i(t){var e,o,n,a,d,s,i,r=document.querySelector("#download-list li[data-download-id='"+t+"']");r&&(e=_XAPP_.getDownloadInfo(t+""),t=_[t],o=r.querySelector(".progress-bar"),n=r.querySelector("#download-speed"),a=r.querySelector("#download-sofar"),r=r.querySelector("button"),d=0==e.total?0:parseInt(e.downloaded/e.total*100),s=e.text_progress,i=e.text_speed,2==e.status?(r.setAttribute("class","icon icon-play"),i=_XAPP_.getStringResource("web_str_dl_status_pause")):3==e.status?(r.setAttribute("class","menu-button"),s=e.text_total,i=_XAPP_.getStringResource("web_str_dl_status_finish"),d=100):1==e.status?(r.setAttribute("class","icon icon-pause"),e.downloaded==e.total&&(d=0)):0==e.status?(r.setAttribute("class","icon icon-pause"),i=_XAPP_.getStringResource("web_str_dl_status_connecting")):4==e.status?(r.setAttribute("class","icon icon-play"),i=_XAPP_.getStringResource("web_str_dl_status_fail")):5==e.status?(r.setAttribute("class","icon icon-play"),i=_XAPP_.getStringResource("web_str_dl_status_wait_wifi")):6==e.status?(r.setAttribute("class","icon icon-play"),i=_XAPP_.getStringResource("web_str_dl_status_waiting")):7==e.status&&(r.setAttribute("class","icon icon-play"),i=_XAPP_.getStringResource("web_str_dl_status_connecting")),r.setAttribute("data-status",e.status),n.innerHTML=i,a.innerHTML=s,t.renderTo(o),t.update(d))}document.addEventListener("DOMContentLoaded",function(){t()},!1),document.addEventListener("event_app_to_page",function(t){var t=t.detail,e=t.transId,t=t.downloadId;"notify_download_start"==e||"notify_download_progress"==e||"notify_download_finish"==e?i(t):"notify_remove_download"==e?(t=document.querySelector("#download-list li[data-download-id='"+t+"']"))&&t.remove():"notify_remove_downloads"==e&&emptyContent()},!1)}();